earth-edges:
  x: 36800
  z: 18430
horse-speed-modifier:
  - SAND;-0.2
  - DIRT_PATH;0.3
  - STONE;0.3
  - COBBLESTONE;0.5
  - STONE_BRICKS;0.5
  - POLISHED_ANDESITE;0.4
  - POLISHED_DIORITE;0.4
  - POLISHED_GRANITE;0.4
  - COBBLED_DEEPSLATE;0.4
  - POLISHED_DEEPSLATE;0.4
  - SMOOTH_QUARTZ;0.4
  - QUARTZ_BLOCK;0.4
  - OAK_PLANKS;0.3
  - SPRUCE_PLANKS;0.3
  - BIRCH_PLANKS;0.3
  - ACACIA_PLANKS;0.3
  - WARPED_PLANKS;0.3
  - CRIMSON_PLANKS;0.3
  - JUNGLE_PLANKS;0.3
messages:
  teleport-confirm: 'Are you sure you want to teleport <distance> blocks?'